"""add game and settings tables

Revision ID: 8be76ea408b0
Revises: 98d545b3662b
Create Date: 2026-07-20 23:00:16.247481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be76ea408b0'
down_revision: Union[str, Sequence[str], None] = '98d545b3662b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_appid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('platform', sa.Enum('pc_steam', 'pc_battlenet', 'ps5', 'xbox', 'switch', 'other', name='platform'), nullable=False),
    sa.Column('status', sa.Enum('wishlist', 'backlog', 'playing', 'completed', 'abandoned', name='status'), nullable=False),
    sa.Column('playtime_minutes', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('steam', 'manual', name='source'), nullable=False),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steam_appid')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_id64', sa.String(), nullable=True),
    sa.Column('steam_vanity_url', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('game')
    # ### end Alembic commands ###
